import type { Metadata } from 'next';
import './globals.css';
import { Roboto } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={roboto.className}>
      <body className='min-h-screen bg-[#ecf4f7]'>
        <h1>layout</h1>
        {children}
      </body>
    </html>
  );
}
